### ISSUE TITLE
Error while serialising AST

### ISSUE THREAD

**Issue by AchalaSB** [taiki-e/syn-serde#10]
Hi, I'm able to generate AST for my code using `syn` crate. Now I'm trying to serialize the AST. while doing i'm getting an error for  line `println!("{}", json::to_string_pretty(&syntax)); `
```
error: the trait bound `syn::File: syn_serde::Syn` is not satisfied
label: the trait `syn_serde::Syn` is not implemented for `syn::File`
```
Here is my code
```
fn main() {
        let source = r#"
            fn main() {
                println!("hello");
            }
        "#;
        let syntax = syn::parse_file(source).unwrap();
        //println!("{:#?}\n", syntax); 
       // Convert AST to JSON
        println!("{}", json::to_string_pretty(&syntax));
}
```
@taiki-e   How can I resolve this error?
Thanks

**Comment by taiki-e** [comment]
Could you check the version of `syn` and `syn-serde`? (`syn-serde` 0.2 is compatible with `syn` 1.0)  I could reproduce this error by using an incompatible version. 

I can also reproduce the same error when using git dependencies.

(If neither of the above, and you are getting this error from the text editor, not the command line -- you may be able to fix it by restarting rls.)
